### ISSUE TITLE
I miss the code!

### ISSUE THREAD

**Issue by jite** [eddie-dunn/test-selection#1]
:)

**Comment by eddie-dunn** [comment]
haha, ja, jag kom på att jag ville städa upp skiten så jag inte skulle
behöva skämmas när jag publicerar den ;)

**Comment by olof** [comment]
Two whole weeks without a resolution? Wtf

**Comment by eddie-dunn** [comment]
@olof yeah, I'm slow.

@jite (most of the) code is up.

**Comment by olof** [comment]
\u2764

**Comment by eddie-dunn** [comment]
```
print('We \u2764 unicode')
```

We ❤ unicode
